### ISSUE TITLE
IDEA: Consider using Base62 instead of Base64

### ISSUE THREAD

**Issue by BjornFJohansson** [MetabolicEngineeringGroupCBMA/seguid#53]
```
# The Base58 alphabet consists of the following characters:

# 123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz

# https://digitalbazaar.github.io/base58-spec


# pip install base58

import hashlib
import base58

seq = "AT"

m = hashlib.sha1()

m.update(seq.encode("ASCII").upper())

csum = base58.b58encode(m.digest()).decode('ASCII').rstrip('=')

assert len(csum) == 27

assert csum == "3XRYrFX1YQgMk1nVZGoPYs4i26H"

# Base64url:
# AT  > slseguid-Ax_RG6hzSrMEEWoCO1IWMGska-4

# Base58
# AT  > slseguid_3XRYrFX1YQgMk1nVZGoPYs4i26H

# If we use an prefix underscore the resulting checksum can be used as an identifier as well. 

slseguid_3XRYrFX1YQgMk1nVZGoPYs4i26H = "tjohej!"

print(slseguid_3XRYrFX1YQgMk1nVZGoPYs4i26H)
```

**Comment by HenrikBengtsson** [comment]
From https://digitalbazaar.github.io/base58-spec/:

> While Base58 does have a number of beneficial usability features, it is not always a good choice for an encoding format. For example, when encoding large amounts of data, it is 2% less efficient than base64. Base58 encoding also has an average worst-case algorithm complexity that is O(n^2). **For these reasons, developers might want to avoid using Base58 for encoding byte strings that are greater than 256 bytes in length.**
> ...
> 7 Quadratic behaviour of base58 algorithms
> 
> In general, when converting from a source base-encoding to a target base-encoding, if the target encoding is not the a numerical power of the source encoding, it is possible for the algorithm to degrade from linear algorithm complexity into quadratic algorithm complexity. That is, converting from base-2 (binary) to base-32 or base-64 can be done with a worst-case algorithm complexity of O(n) time, but converting from base-2 to base-58 has a worst-case complexity of O(n^2). **In short, base-58 does not work well for encoding large byte values.**
> 
> **Implementers are urged to ensure that their production software imposes limits on input size. Encoding values greater than 256 bytes in base58 is NOT RECOMMENDED.**

**Comment by BjornFJohansson** [comment]
We encode the SHA1checksum, which is 160 bits...

**Comment by HenrikBengtsson** [comment]
Did you consider [Base62](https://en.wikipedia.org/wiki/Base62)?

**Comment by HenrikBengtsson** [comment]
Regarding Base58:  From Section 'Introduction' of <https://digitalbazaar.github.io/base58-spec/>:

"Fifth, unlike Base64, there is no byte padding ..."

> Is the base58 encoded hex value of SHA1 always 27 chars long?

No. It can result in up to 28 characters, e.g.

```sh
$ python -c "import hashlib; import base58; m = hashlib.sha1(); m.update('1'.encode('ASCII')); print(len(base58.b58encode(m.digest())))"
27

$ python -c "import hashlib; import base58; m = hashlib.sha1(); m.update('0'.encode('ASCII')); print(len(base58.b58encode(m.digest())))"
28
```

In contrast, Base64 is padded (with `=`) so that the output "length is a multiple of four" (https://en.wikipedia.org/wiki/Base64#Output_padding).  This is why Base64 on SHA-1 (160 bits) is always 28 characters long.

**Comment by BjornFJohansson** [comment]
```
# pip install base58, pybase62

import hashlib
import base58
import base64
import base62

seq = "AT"

def b62(arg):
    return base62.encodebytes(arg).encode()


checksums = [hashlib.sha1, hashlib.sha224, hashlib.sha256]
encodings = [base64.urlsafe_b64encode,b62, base58.b58encode]

for cs in checksums:
    print()
    for enc in encodings:

        m = cs(seq.upper().encode("ASCII")).digest()
        csum = "xxseguid_" + enc(m).decode("ASCII").rstrip('=')
    
        print(csum, len(csum))
        print()

"""
xxseguid_Ax_RG6hzSrMEEWoCO1IWMGska-4 36

xxseguid_RdbB3kl78Fn1dQqYXBkmRZIWsQ 35

xxseguid_3XRYrFX1YQgMk1nVZGoPYs4i26H 36


xxseguid_7qiyC9V0C-_gtrzzKSNq76ME4DmMo0SJK630-g 47

xxseguid_C4RAmfXPnbqRm0qyz6T5eMyyDO8cTE3UYOH3wg 47

xxseguid_3TNWWzTfoJntYDZTT4QRGLQwtzyKm3WxU9PhsTo 48


xxseguid_61RCcFlp3I2l36yPlljcaKzatbt2Nbp8xVHjiUFqw04 52

xxseguid_tnpkuXLsDwfzog5QMz29nbgZW4UmRmbCkdlhSi0SXmA 52

xxseguid_GqdL4AUQF8SvpWWw92pesyPX8qK72dGL1fWqa6fGmBGq 53
"""
```

**Comment by HenrikBengtsson** [comment]
DECISION 2024-01-04: 
* After a quick call, we concluded that Base62 is better than Base58. The only reason Base58 would be better than Base62 would be implementation availability.
* The remaining decision is, therefore, should we keep Base64url or move to Base62.

**Comment by HenrikBengtsson** [comment]
# Base62 vs Base64

Advantages of Base62 over Base64:

* Base62 checksums work as identifier in most languages (probably rarely needed)
* Base62 checksums are easier to cut'n'paste; you get the whole checksum by double-clicking
* ...?

Advantages of Base64 over Base62:

* Base64 is widely implemented
* Base64 is faster by design, because it can operate on 4/8-bits at the time
* ...?

No biggies:

* Length of Base62 and Base64 checksums are the same (or only differ by one)
* ...?


# Actions

* [ ] Identify existing implementations in Python, R, C, Tcl, Rust, JavaScript, ...
* [ ] Benchmark Base62 and Base64 encoding algorithms/implementations at the lowest level, i.e. vanilla Python and R without **seguid** code

**Comment by HenrikBengtsson** [comment]
Benchmarking Python's Base62 and Base64 implementations for SHA-1, SHA-224, SHA-256, gives that Base62 is ~10-20 times slower than Base64 on a string of length 20-32.

# Details

```py
import hashlib
import base64
import base62  ## PyPi 'pybase62'
import timeit
import random
import string

def base62enc(arg):
    return base62.encodebytes(arg).encode()

def base64enc(arg):
    return base64.urlsafe_b64encode(arg)

times = 100000
checksums = [hashlib.sha1, hashlib.sha224, hashlib.sha256]

## A "random" sequence (doesn't really matter - only the checksum hash
seq = 'ACGT'

for checksum in checksums:
    ## Generate SHA-1 checksum (it's the length of the hash that matters)
    hash = checksum(seq.upper().encode("ASCII")).digest()
    
    ## Benchmark
    t62 = timeit.timeit('base62enc(hash)', globals = globals(), number = times)
    t64 = timeit.timeit('base64enc(hash)', globals = globals(), number = times)
    
    ## Display results
    print("base62enc(<%d-hash>): %.3f seconds/million encodings [%.1fx]" % (len(hash), 1e6 * t62 / times, t62/t64))
    print("base64enc(<%d-hash>): %.3f seconds/million encodings [ 1.0x]" % (len(hash), 1e6 * t64 / times))
```

gives

```
base62enc(<20-hash>): 3.317 seconds/million encodings [11.6x]
base64enc(<20-hash>): 0.287 seconds/million encodings [ 1.0x]
base62enc(<28-hash>): 4.686 seconds/million encodings [15.0x]
base64enc(<28-hash>): 0.313 seconds/million encodings [ 1.0x]
base62enc(<32-hash>): 5.283 seconds/million encodings [17.0x]
base64enc(<32-hash>): 0.311 seconds/million encodings [ 1.0x]
```

**Comment by HenrikBengtsson** [comment]
Good news, the algorithms for Base64 encoding and Base62 encoding are both $O(n)$, i.e. linear in the length of the input string.

The greater performance of Base64 implementations comes from being able to work with multiples of 8 bits (whole bytes), instead of multiples of 5–6 bits. Compilers can optimize code towards CPU instructions, registries, and memory caches when working with whole bytes.


# Details

## Base64 encoding

The Base64 encoding algorithm uses an alphabet of 64 characters, which can be represented using $log_2(64)$ = 6 bits. Since the input is 8-bit ASCII, this means that an ASCII string can be processed in chunks of three characters. This is because 3 ASCII chars * 8 bits/ASCII char = 24 bits, which corresponds to 4 Base64 characters, i.e. 4 Base64 chars * 6 bits/Base64 char = 24 bits.  This makes it quick to process. For every 3 ASCII characters, we can use bit-shifting to pull out the 4 Base64 characters.  Alternatively, we could have an 8*8*8 lookup array of all 512 possible ASCII tuples and map those to the corresponding 4 Base64 characters.

See for instance <https://en.wikibooks.org/wiki/Algorithm_Implementation/Miscellaneous/Base64>


## Base62 encoding

The Base62 encoding algorithm uses an alphabet of 62 characters, which can be represented using $log_2(62)$ = 5.70044 bits on average.  Contrary to Base64, we cannot partion the input into chunks that can be encoded independently.  Instead, we need to operate on the input bit stream in chunks of 5-6 bits per Base62 characters.  The gist is to read 6 bits, and if we only needed 5 bits, we roll back one bit.  Given the 5 or 6 bits, we map the integer value to the corresponding letter in the Base62 alphabet.  This process is linear in the number of ASCII characters.

See for instance <https://github.com/glowfall/base62/blob/master/Base62.java#L66-L93>.

See also <https://stackoverflow.com/a/75000403/1072091>

**Comment by HenrikBengtsson** [comment]
DECISION from 2024-01-22 call:

We will stick with Base64url, because:

* With Base62, we are forced to introduce a padding symbol, e.g. =.
* There appear to be different versions of Base62 encoding.
* Implementations of Base62 are much less common, which lowers the chances for someone to implement SEGUIDv2 elsewhere.
